case:
 goal:
  x: 200.
  yVal: 125.
  psi: 1.5701

 actual:
  X0:
   x: 0.0
   yVal: 0.0
   v: 0.0
   r: 0.0
   psi: 1.57079632679
   sa: 0.0
   ux: 0.0
   ax: 0.0

  obstacle:
   num: 3
   radius: [2.0,2.0,3.0]
   length: [4.0,4.0,4.0]
   x0: [5.,-5,10]
   y0: [10.,15,25]
   vx: [0,0,0.0]
   vy: [0,0,0]

 assumed:
  obstacle:
   num: 10
   radius: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
   length: [4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0]
   x0: [-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0]
   y0: [0,2,4,6,8,10,12,14,16,18]
   vx: [0,0,0,0,0,0,0,0,0,0]
   vy: [0,0,0,0,0,0,0,0,0,0]
