case:
 goal:
  x: 0.
  yVal: 125.
  psi: 1.5701
  tol: 4

 actual:
  X0:
   x: 0.0
   yVal: 0.0
   z: 0.5
   v: 0.0
   r: 0.0
   phi: 0.0
   theta: 0.0
   psi: 1.57079632679
   sa: 0.0
   ux: 0.0
   ax: 0.0
  obstacle:
   num: 3
   radius: [5.,10.,2.]
   length: [5.,5.,5.]
   x0: [5.,-20.,0.]
   y0: [50.,75.,65.]
   vx: [0.,0.,0.]
   vy: [0.,0.,0.]

 assumed:
  obstacle:
   num: 10
   radius: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
   length: [4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0]
   x0: [-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0]
   y0: [0,2,4,6,8,10,12,14,16,18]
   vx: [0,0,0,0,0,0,0,0,0,0]
   vy: [0,0,0,0,0,0,0,0,0,0]
