case:
 goal:
  x: 200.
  yVal: 125.
  psi: 1.5701
  tol: 15.

 actual:
  X0:
   x: 200.0
   yVal: 0.0
   v: 0.0
   r: 0.0
   psi: 1.57079632679
   sa: 0.0
   ux: 17.0
   ax: 0.0
  obstacle:
   num: 3
   radius: [5.,4.,2.]
   length: [5.,5.,5.]
   x0: [205,180,200]
   y0: [57,75,63]
   vx: [-2,-1,-0.5]
   vy: [0,1,6.]
