system:
 vehicle_description:
  flags:
   running: true
   postion_update_external: false
   lidar_initialized: false
   obstacles_initialized: false
 obstacle_detector:
  flags:
   running: true
   initialized: false
 paused: true
step_simulation: 1.0
