mavs:
 # robot
 X0:
   x: 0.0
   y: 0.0
   v: 0.0
   r: 0.0
   psi: 1.57079632679
   sa: 0.0
   ux: 0.0
   ax: 0.0

 # obstacles
 obs:
   num: 3
   radius: [2.0,2.0,3.0]
   length: [4.0,4.0,4.0]
   x0: [5.,-5,10]
   y0: [10.,15,25]
   vx: [0,0,0.0]
   vy: [0,0,0]
