system:
 planner: ros_base_planner

 params:
  step_size: 0.001
  
 flags:
  goal_attained: false
  initialized: false
  paused: true

 vehicle_description:
  flags:
   running: true
   lidar_initialized: false
   obstacles_initialized: false
   postion_update_external: false

 ros_base_planner:
  nameSpace: ros_base_planner
  flags:
   running: true
   initialized: false
   known_environment: true
   goal_known: true
